// Synthetic demo media, generated on first run so the repo ships no footage of a real person.
//   inputs/_demo/speaker.mp4  faceless silhouette + silent audio (talking-head demo, webcam card)
//   inputs/_demo/screen.mp4   test pattern (screen-share demo)
//   inputs/face-track.js/.json  head boxes for the silhouette (only written when missing; detect-face.py
//                               overwrites them with the track of your own footage)
// All of it is git-ignored. Video needs ffmpeg on PATH. Replace them with your own files in inputs/ when you make a real video.
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const DEMO_DURATION = 21.92;

// Silhouette geometry. The generated demo face track uses the head box around it.
const HEAD = { cx: 965, cy: 430, rx: 190, ry: 240 };
const HEAD_BOX = { x0: 745, y0: 170, x1: 1185, y1: 690 };
const FACE_FPS = 10;

export const FFMPEG_MISSING = 'ffmpeg not found on PATH - install it (macOS: brew install ffmpeg, Windows: winget install ffmpeg)';

const ff = (args) => {
  const r = spawnSync('ffmpeg', ['-loglevel', 'error', '-y', ...args], { stdio: 'inherit' });
  if (r.error && r.error.code === 'ENOENT') { console.error(FFMPEG_MISSING); return false; }
  return r.status === 0;
};

const MAKERS = {
  'inputs/_demo/speaker.mp4': (out) => {
    const head = `lt(pow((X-${HEAD.cx})/${HEAD.rx},2)+pow((Y-${HEAD.cy})/${HEAD.ry},2),1)`;
    const body = `lt(pow((X-${HEAD.cx})/560,2)+pow((Y-1160)/380,2),1)`;
    const neck = `lt(abs(X-${HEAD.cx}),85)*gt(Y,600)*lt(Y,860)`;
    const person = `gt(${head}+${body}+${neck},0)`;
    const glow = `exp(-(pow(X-${HEAD.cx},2)+pow(Y-420,2))/500000)`;
    const ch = (bg, fg) => `if(${person},${fg}-0.03*(Y-300),${bg[0]}+${bg[1]}*${glow})`;
    const still = out.replace(/\.mp4$/, '.png');
    return ff(['-f', 'lavfi', '-i', 'color=c=black:s=1920x1080', '-frames:v', '1',
      '-vf', `format=rgb24,geq=r='${ch([14, 30], 64)}':g='${ch([18, 34], 68)}':b='${ch([26, 48], 80)}'`, still]) &&
      ff(['-loop', '1', '-framerate', '30', '-i', still, '-f', 'lavfi', '-i', 'anullsrc=r=48000:cl=stereo',
        '-t', String(DEMO_DURATION), '-vf', 'noise=alls=5:allf=t,format=yuv420p', '-c:v', 'libx264', '-crf', '26',
        '-c:a', 'aac', '-shortest', out]) && (fs.rmSync(still), true);
  },
  'inputs/_demo/screen.mp4': (out) => ff(['-f', 'lavfi', '-i', `testsrc2=size=1920x1080:rate=30:duration=${DEMO_DURATION}`,
    '-an', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-crf', '28', out])
};

// Writes inputs/face-track.js + .json for the demo silhouette when they are missing. Never overwrites:
// once detect-face.py has written the track of your footage, that track stays. Returns true if it wrote.
export function ensureFaceTrack() {
  const json = path.join(ROOT, 'inputs/face-track.json'), js = path.join(ROOT, 'inputs/face-track.js');
  if (fs.existsSync(json) && fs.existsSync(js)) return false;
  const n = Math.ceil(DEMO_DURATION * FACE_FPS) + 1;   // covers 0 .. DEMO_DURATION
  const track = Array.from({ length: n }, (_, i) => ({ t: Math.round(i * 100 / FACE_FPS) / 100, ...HEAD_BOX }));
  const data = { source: '_demo/speaker.mp4 (synthetic silhouette)', fps: FACE_FPS, frame: [1920, 1080], detected: n, total: n, track };
  fs.mkdirSync(path.dirname(json), { recursive: true });
  fs.writeFileSync(json, JSON.stringify(data, null, 1) + '\n');
  fs.writeFileSync(js, '/* demo face track for inputs/_demo/speaker.mp4 (generated by scripts/demo-media.mjs).\n' +
    '   scripts/detect-face.py replaces it with the track of your own footage. Git-ignored. */\n' +
    'window.__hfFace = ' + JSON.stringify(data) + ';\n');
  console.log('generated demo face track: inputs/face-track.js');
  return true;
}

// Returns the list of sources it could not provide (not a demo file, or ffmpeg failed).
// `base` is the folder the page lives in (sources are relative to it); demo clips are always made under ROOT.
export function ensureDemoMedia(srcs, base = ROOT) {
  const missing = [];
  for (const src of srcs) {
    if (fs.existsSync(path.resolve(base, src))) continue;
    const make = MAKERS[src];
    if (make) {
      fs.mkdirSync(path.join(ROOT, 'inputs/_demo'), { recursive: true });
      const out = path.join(ROOT, src);
      if (fs.existsSync(out) || make(out)) { console.log('generated demo media: ' + src); continue; }
    }
    missing.push(src);
  }
  return missing;
}

export function mediaIn(html) {
  return [...html.matchAll(/<(?:video|audio)\b[^>]*\bsrc="([^"]+)"/g)].map((m) => m[1]);
}

// CLI: node scripts/demo-media.mjs [index.html ...]  ensures the face track and the media every given page references.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const pages = process.argv.slice(2).length ? process.argv.slice(2) : ['index.html'];
  ensureFaceTrack();
  const missing = pages.flatMap((p) => {
    const file = fs.existsSync(p) ? p : path.join(ROOT, p);
    return ensureDemoMedia(mediaIn(fs.readFileSync(file, 'utf8')), path.dirname(path.resolve(file)));
  });
  if (missing.length) {
    console.error('missing media -> ' + missing.join(', ') + '\nPut your files in inputs/ and point the <video> src at them.');
    process.exit(1);
  }
}
