#!/usr/bin/env python3
"""Detect the speaker's face once and write inputs/face-track.json.

Usage (opencv lives in a throwaway venv, not in the project):
  python3 -m venv /tmp/hf-venv && /tmp/hf-venv/bin/pip install opencv-python-headless numpy
  /tmp/hf-venv/bin/python scripts/detect-face.py inputs/speaker.mp4 inputs/face-track.json

Output boxes are in raw 1920x1080 frame coordinates and cover the HEAD (hair to chin),
sampled at 10 fps, median-smoothed so the box does not jitter.
"""
import json, subprocess, sys, tempfile, os, glob
import cv2, numpy as np

src = sys.argv[1] if len(sys.argv) > 1 else "inputs/speaker.mp4"
dst = sys.argv[2] if len(sys.argv) > 2 else "inputs/face-track.json"
FPS, SCALE = 10, 0.5
W, H = 1920, 1080

tmp = tempfile.mkdtemp()
subprocess.run(["ffmpeg", "-loglevel", "error", "-i", src, "-vf", f"fps={FPS},scale={int(W*SCALE)}:{int(H*SCALE)}",
                os.path.join(tmp, "f_%04d.png")], check=True)
frames = sorted(glob.glob(os.path.join(tmp, "f_*.png")))
casc = [cv2.CascadeClassifier(cv2.data.haarcascades + n) for n in
        ("haarcascade_frontalface_alt2.xml", "haarcascade_frontalface_default.xml")]

raw = []
for p in frames:
    g = cv2.equalizeHist(cv2.cvtColor(cv2.imread(p), cv2.COLOR_BGR2GRAY))
    best = None
    for c in casc:
        for f in c.detectMultiScale(g, 1.08, 5, minSize=(90, 90)):
            if best is None or f[2] * f[3] > best[2] * best[3]:
                best = f
        if best is not None:
            break
    raw.append(None if best is None else [v / SCALE for v in best])

if not any(raw):
    sys.exit('detect-face: no frontal face found in ' + src + ' (check framing/lighting); nothing written')

# fill gaps, then median-smooth
arr = np.array([r if r else [np.nan] * 4 for r in raw], dtype=float)
for i in range(4):
    idx = np.arange(len(arr)); ok = ~np.isnan(arr[:, i])
    arr[:, i] = np.interp(idx, idx[ok], arr[ok, i])
k = 7
pad = np.pad(arr, ((k // 2, k // 2), (0, 0)), mode="edge")
sm = np.array([np.median(pad[i:i + k], axis=0) for i in range(len(arr))])

# haar box already spans hairline-to-chin; add the hair above and a small side margin
track = []
for i, (x, y, w, h) in enumerate(sm):
    hx0, hy0 = x - 0.05 * w, y - 0.33 * h
    hx1, hy1 = x + 1.05 * w, y + 1.0 * h
    track.append({"t": round(i / FPS, 2), "x0": round(hx0), "y0": round(hy0), "x1": round(hx1), "y1": round(hy1)})

json.dump({"source": os.path.basename(src), "fps": FPS, "frame": [W, H], "detected": sum(1 for r in raw if r), "total": len(raw), "track": track},
          open(dst, "w"), indent=1)
js = dst.rsplit(".", 1)[0] + ".js"
open(js, "w").write("/* generated by scripts/detect-face.py - do not edit */\nwindow.__hfFace = " + json.dumps(json.load(open(dst))) + ";\n")
print(f"detected {sum(1 for r in raw if r)}/{len(raw)} frames -> {dst}")
