#!/usr/bin/env node
// Prepares a project folder (default projects/screen-share) for check/preview/render. Run automatically by the
// share:* and speaker:* npm scripts (any cwd):  node scripts/sync-share.mjs [projects/<name>] [--static-camera]
//   --canvas vertical  1080x1920 for short-form reels: writes components/canvas.js (size + platform safe zones), resizes every
//                    template's canvas and uses inputs/face-track.vertical.js (the demo makes a portrait silhouette).
//   --static-camera  for projects that never move a camera (speaker cutout): writes an empty components/camera.js copy,
//                    so templates do not apply the talking-head demo's camera moves to the face box.
//  1. Real copies of components/ + compositions/tpl/ (the HyperFrames bundler reads symlinked sources as EMPTY).
//  2. inputs/ + assets/ links (directory junctions on Windows, relative symlinks elsewhere): media is served, not bundled.
//  3. Demo face track (inputs/face-track.js) when missing, then a media check: every <video>/<audio> src in the
//     project's index.html must exist. Missing demo clips (inputs/_demo/*) are generated (needs ffmpeg);
//     any other missing file stops with a clear message.
import fs from 'node:fs';
import path from 'node:path';
import { ensureDemoMedia, ensureFaceTrack, mediaIn, ROOT, VERTICAL } from './demo-media.mjs';

const args = process.argv.slice(2);
const DEST = (args.find((a) => a.startsWith('projects/')) || 'projects/screen-share').replace(/\/$/, '');
const STATIC_CAMERA = args.includes('--static-camera');
const canvasArg = args.indexOf('--canvas') >= 0 ? args[args.indexOf('--canvas') + 1] : 'landscape';
if (!['landscape', 'vertical'].includes(canvasArg)) { console.error('--canvas must be landscape or vertical'); process.exit(1); }
const IS_VERTICAL = canvasArg === 'vertical';
const dest = path.join(ROOT, DEST);

const copy = (from, to) => {
  fs.rmSync(to, { recursive: true, force: true });
  fs.mkdirSync(to, { recursive: true });
  for (const f of fs.readdirSync(from)) {
    const s = path.join(from, f);
    if (fs.statSync(s).isFile()) fs.copyFileSync(s, path.join(to, f));
  }
};
copy(path.join(ROOT, 'components'), path.join(dest, 'components'));
copy(path.join(ROOT, 'compositions/tpl'), path.join(dest, 'compositions/tpl'));
if (IS_VERTICAL) {
  // Platform interface covers roughly the top 12%, the bottom 22% and a strip on the right (buttons): keep text out of it.
  fs.writeFileSync(path.join(dest, 'components/canvas.js'),
    '/* generated by scripts/sync-share.mjs --canvas vertical (edit the numbers in scripts/sync-share.mjs) */\n' +
    '(function (root) {\n  root.__hfCanvas = { name: "vertical", w: 1080, h: 1920, safe: { top: 230, bottom: 430, left: 64, right: 150 }, caption: { bottom: 470, size: 60 } };\n' +
    '  if (typeof document !== "undefined" && document.documentElement) {\n    var d = document.documentElement; d.style.setProperty("--cw", "1080px"); d.style.setProperty("--ch", "1920px"); d.classList.add("vertical");\n  }\n})(typeof window !== "undefined" ? window : this);\n');
  const tplDir = path.join(dest, 'compositions/tpl');
  for (const f of fs.readdirSync(tplDir)) {
    const p = path.join(tplDir, f);
    const h = fs.readFileSync(p, 'utf8')
      .replace(/data-width="1920" data-height="1080"/g, 'data-width="1080" data-height="1920"')
      .replace(/inputs\/face-track\.js/g, 'inputs/face-track.vertical.js');
    fs.writeFileSync(p, h);
  }
}
if (STATIC_CAMERA) {
  fs.writeFileSync(path.join(dest, 'components/camera.js'),
    '/* generated by scripts/sync-share.mjs --static-camera: this project never moves the camera */\nwindow.__hfCamera = { rig: "#camera-rig", origin: [' + (IS_VERTICAL ? '540, 960' : '960, 540') + '], cuts: [], punch: 1, moves: [] };\n');
}

for (const name of ['inputs', 'assets']) {
  const link = path.join(dest, name), target = path.join(ROOT, name);
  fs.mkdirSync(target, { recursive: true });
  // older checkouts made absolute symlinks: swap them for relative ones (POSIX only)
  let old = null; try { old = fs.lstatSync(link).isSymbolicLink() ? fs.readlinkSync(link) : null; } catch { /* no link yet */ }
  if (process.platform !== 'win32' && old && path.isAbsolute(old)) fs.rmSync(link, { force: true });
  if (!fs.existsSync(link)) {
    fs.rmSync(link, { force: true });   // a dangling link from a moved checkout
    // junctions need an absolute target (Windows); symlinks stay relative so the repo can move
    if (process.platform === 'win32') fs.symlinkSync(target, link, 'junction');
    else fs.symlinkSync(path.relative(dest, target), link);
  }
}

ensureFaceTrack(IS_VERTICAL ? VERTICAL : undefined);
const missing = ensureDemoMedia(mediaIn(fs.readFileSync(path.join(dest, 'index.html'), 'utf8')), dest);
if (missing.length) {
  console.error('\n' + path.basename(DEST) + ': missing media -> ' + missing.join(', ') +
    '\nPut your files in inputs/ and point the <video> src in ' + DEST + '/index.html at them.');
  process.exit(1);
}
console.log('synced components + compositions/tpl + media links -> ' + DEST);
